"""add friendship model

Revision ID: 03db466e10a7
Revises: 1ca236268ab0
Create Date: 2026-05-13 14:56:03.218472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03db466e10a7'
down_revision = '1ca236268ab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.uid'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friendship')
    # ### end Alembic commands ###
