"""add challenge model

Revision ID: 7056ac216709
Revises: 97a9632d8370
Create Date: 2026-05-14 15:39:16.752623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7056ac216709'
down_revision = '97a9632d8370'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenger_id', sa.Integer(), nullable=False),
    sa.Column('challenged_id', sa.Integer(), nullable=False),
    sa.Column('photo_ids', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('challenger_ready', sa.Boolean(), nullable=True),
    sa.Column('challenged_ready', sa.Boolean(), nullable=True),
    sa.Column('challenger_score', sa.Integer(), nullable=True),
    sa.Column('challenged_score', sa.Integer(), nullable=True),
    sa.Column('challenger_round', sa.Integer(), nullable=True),
    sa.Column('challenged_round', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['challenged_id'], ['user.uid'], ),
    sa.ForeignKeyConstraint(['challenger_id'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('challenges')
    # ### end Alembic commands ###
