"""add photos table

Revision ID: c705725ba6da
Revises: cd5f5fba1612
Create Date: 2026-05-12 11:05:58.239346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c705725ba6da'
down_revision = 'cd5f5fba1612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=256), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('pid')
    )

    # ### end Alembic commands ###


def downgrade():
    op.drop_table('photos')
    # ### end Alembic commands ###
